// Env is generated by `wrangler types` in worker-configuration.d.ts

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const securityHeaders: Record<string, string> = {
			'Content-Security-Policy':
				"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob:; connect-src 'self'; manifest-src 'self';",
			'X-Content-Type-Options': 'nosniff',
			'X-Frame-Options': 'DENY',
			'Referrer-Policy': 'strict-origin-when-cross-origin',
			'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
		};

		if (request.method !== 'GET') {
			return new Response('Method not allowed', {
				status: 405,
				headers: securityHeaders,
			});
		}

		try {
			const response = await env.ASSETS.fetch(request);

			return new Response(response.body, {
				status: response.status,
				statusText: response.statusText,
				headers: {
					...Object.fromEntries(response.headers.entries()),
					...securityHeaders,
				},
			});
		} catch (e) {
			console.error(
				JSON.stringify({
					message: 'asset fetch failed',
					error: e instanceof Error ? e.message : String(e),
					url: request.url,
				})
			);
			return new Response('Not found', { status: 404, headers: securityHeaders });
		}
	},
} satisfies ExportedHandler<Env>;
